### PR TITLE
[fix #254] Bug fixes for UTXO Graph based enhancement

### LINKED ISSUE #254: Bug fixes for UTXO Graph based enhancement

### PR DESCRIPTION
**Pull request by stplaydog**

### CODE REVIEW

**Comment by lhfbc** [comment]
Just rebase.

File: src/main/java/com/iota/iri/service/API.java [hunk 1]
```diff
@@ -1365,15 +1365,23 @@ public void shutDown() {
     private synchronized AbstractResponse storeMessageStatement(final String address, final String message, final String tag) throws Exception {
         List<Hash> txToApprove = new ArrayList<Hash>();
         try {
-            txToApprove = getTransactionToApproveTips(3, Optional.empty());
+            txToApprove = getTransactionToApproveTips(15, Optional.empty());
         } catch (NullPointerException e) {
```
Comment (stplaydog) [inline src/main/java/com/iota/iri/service/API.java:1369]: should be simplified

File: src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java [hunk 2]
```diff
@@ -559,6 +559,11 @@ public long getTotalTxns() {
                 Map<Hash, Set<Hash>> subGraph = buildSubGraph(diff);
                 List<Hash> noBeforeInTmpGraph = subGraph.entrySet().stream().filter(e -> CollectionUtils.isEmpty(e.getValue())).map(Map.Entry::getKey).collect(Collectors.toList());
                 //TODO consider using SPECTR for sorting
+                for(Hash s : noBeforeInTmpGraph) {
```
Comment (stplaydog) [inline src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java:562]: why ?

**Review by lhfbc — APPROVED** [review]
