### PR TITLE
[fix #212] get total order before get balance.

### LINKED ISSUE #212: fix get_balance bug
If we send transactions serially, it will be ok, and everyone's balance is right.
But if we send transactions parallelly, the amount's balance will go wrong, and double-spending may be happening. So we need to get a total order of all transactions and skip the spent utxo when getting balance.

### PR DESCRIPTION
**Pull request by lhfbc**

### CODE REVIEW

**Comment by lhfbc** [comment]
@jdyuankai, there may be something wrong.
Before doing any operation, calls for 'totalTopOrder' will return nothing, but IMO it should return the coinbase transaction.

File: src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java [hunk 1]
```diff
@@ -405,19 +407,38 @@ private String generateHash(String txnStr) {
     }
 
     public long getBalance(String account) {
+        LocalInMemoryGraphProvider provider = (LocalInMemoryGraphProvider)tangle.getPersistenceProvider("LOCAL_GRAPH");
```
Comment (stplaydog) [inline src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java:410]: in TransactionDataTest, you need to initialize tangle, or else the test's gonna fail.

**Comment by lhfbc** [comment]
Test:
1. 
```
cd scripts/examples
./conflux_dag_two_nodes.sh
./start_cli_two_nodes.sh
./parallel_put_txn_two_nodes.sh
```
2. get the balance of A, a, b, c ...z, and the sum of all these balance should be 10000.

**Review by wangyh2016 — APPROVED** [review]

**Review by stplaydog — APPROVED** [review]
