### PR TITLE
[fix #288] Dag out of order (fix on fix)

### LINKED ISSUE #288: Dag out of order
**问题描述**

  多台机器之间如果一次同步多个数据节点，如果不能严格按照先前后的顺序会导致数据节点在它们之间的得分不一致，最终影响交易的确认。

---

**解决方法**  

只计算可以回溯到genesis的节点的score，不可回溯的节点加入重试队列。回溯规则是：必须trunk和branch两条路径均可以回溯，为了性能需要，一次回溯成功会把回溯成功的节点记录下来，如果后续节点的前驱节点可以回溯到有记录时点则视为回溯完成。

---

**更新updateScore逻辑**

- 判断是否可回溯，若不可回溯把当前节点不可回溯节点列表，方法结束。（新增不可回溯节点不会导致其他不可回溯节点状态变化），否则进行第二步骤；
- 把可回溯节点加入可回溯节点列表；
- 计算得分；
- 重新处理不可回溯节点（新增可回溯节点会导致其他不可回溯节点状态变化），若状态变化未可回溯则重新计算得分，否则重新装回不可回溯队列。

```
// 未能回溯到genesis的节点
Queue<Hash> unTracedNodes;

// 保存可回溯的节点，最坏的情况是保存了整个graph，空间换时间。
Set<Hash> tracedNodes;

// 回溯方法，能够回溯到genesis或者已回溯节点都算作回溯成功
boolean traceToGenesis(Hash h);

// 回溯逻辑只影响更新，且computeScore目前未走到此分支0.2版本暂不考虑
com.iota.iri.storage.localinmemorygraph.LocalInMemoryGraphProvider#updateScore
```

**增加rebuildParentScore逻辑**

```
// 每取到一个节点就重构一次parentScore，只保证最终得分正确性
// TODO 单独启动一个线程验证parent节点得分一定大于子节点，否则告警。
void rebuildParentScore(Hash h);
```

### PR DESCRIPTION
**Pull request by stplaydog**

### CODE REVIEW

File: src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java [hunk 1]
```diff
@@ -332,9 +332,10 @@ private void updateScore(Hash vet) {
             if(BaseIotaConfig.getInstance().getStreamingGraphSupport()){
                 if (BaseIotaConfig.getInstance().getConfluxScoreAlgo().equals("CUM_WEIGHT")) {
                     score = CumWeightScore.update(graph, score, vet);
+		    parentScore = CumWeightScore.computeParentScore(parentGraph, parentRevGraph);
```
Comment (stplaydog) [inline src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java:335]: FIXME in the future

**Review by lhfbc — APPROVED** [review]
